### ISSUE TITLE
Not able to connect to cassandra , throwing exception com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces

### ISSUE THREAD

**Issue by bhuvanrawal** [tenmax/cqlkit#5]
Both cql2json and cql2csv are throwing this exception and im not able to get results.
./cql2json -q 'select \* from films_property'
Exception in thread "main" com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /30.0.3.217:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:82)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1307)
    at com.datastax.driver.core.Cluster.init(Cluster.java:159)
    at com.datastax.driver.core.Cluster.connect(Cluster.java:249)
    at io.tenmax.cqlkit.SessionFactory.<init>(SessionFactory.java:62)
    at io.tenmax.cqlkit.SessionFactory.newInstance(SessionFactory.java:91)
    at io.tenmax.cqlkit.AbstractMapper.run(AbstractMapper.java:215)
    at io.tenmax.cqlkit.AbstractMapper.start(AbstractMapper.java:117)
    at io.tenmax.cqlkit.CQL2JSON.main(CQL2JSON.java:107)

**Comment by phstudy** [comment]
This should be caused by Cassandra Java driver 2.x. Could you try with the latest cqlkit?
