### ISSUE TITLE
Running command without args should display help

### ISSUE THREAD

**Issue by erhhung** [tenmax/cqlkit#6]
It's not very user friendly when running a program without args immediately throws an exception.
If no query is specified in any of the 3 methods, then the program should display help before even trying to connect to a cluster.

```
> cql2json
Exception in thread "main" java.lang.IllegalArgumentException: Cannot build a cluster without contact points
    at com.datastax.driver.core.Cluster.checkNotEmpty(Cluster.java:118)
    at com.datastax.driver.core.Cluster.<init>(Cluster.java:110)
    at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:179)
    at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1190)
    at io.tenmax.cqlkit.SessionFactory.<init>(SessionFactory.java:60)
    at io.tenmax.cqlkit.SessionFactory.newInstance(SessionFactory.java:91)
    at io.tenmax.cqlkit.AbstractMapper.run(AbstractMapper.java:215)
    at io.tenmax.cqlkit.AbstractMapper.start(AbstractMapper.java:117)
    at io.tenmax.cqlkit.CQL2JSON.main(CQL2JSON.java:107)

```

**Comment by phstudy** [comment]
Fixed in #14
